---
name: testing

"on":
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Setup gnupg
      #   id: gnupg
      #   uses: crazy-max/ghaction-import-gpg@v6
      #   with:
      #     gpg_private_key: ${{ secrets.GNUPG_KEY }}
      #     passphrase: ${{ secrets.GNUPG_PASSWORD }}
      #     trust_level: 5

      - name: Setup python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      # - name: Setup sops
      #   uses: nhedger/setup-sops@v2

      - name: Setup testing
        id: setup
        uses: helm/chart-testing-action@v2.6.1

      - name: Setup helm
        id: helm
        uses: azure/setup-helm@v4

      # - name: Helm plugins
      #   id: plugins
      #   run: |
      #     helm plugin install https://github.com/jkroepke/helm-secrets

      # - name: Decrypt secrets
      #   id: secrets
      #   run: |
      #     for FILE in $(find stable -iname \*.enc); do
      #       helm secrets decrypt ${FILE} >| ${FILE%.enc}.yaml
      #       echo >> ${FILE%.enc}.yaml
      #     done

      - name: Detect testing
        id: detect
        run: |
          CHANGED=$(ct list-changed --config ct.yaml)

          if [[ -n "${CHANGED}" ]]; then
            echo "changed=true" >> "${GITHUB_OUTPUT}"
          fi

      - name: Run Linting
        id: linting
        if: steps.detect.outputs.changed == 'true'
        run: |
          ct lint --config ct.yaml

      - name: Create kind
        id: kind
        if: steps.detect.outputs.changed == 'true'
        uses: helm/kind-action@v1.10.0

      - name: Run testing
        id: testing
        if: steps.detect.outputs.changed == 'true'
        run: |
          ct install --config ct.yaml

...
