---
name: updates

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  updates:
    runs-on: ubuntu-latest
    if: github.repository == 'cloudhippie/charts'

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Setup golang
        id: golang
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20.0

      - name: Update versions
        id: updater
        run: |
          go run ./internal/cmd/updater .

      - name: Create request
        id: request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: updated-versions
          delete-branch: true
          title: "chore: updated versions"
          body: "New versions found, please review!"
          assignees: tboerger
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Create issue
        id: issue
        if: failure()
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
          GITHUB_SERVER_URL: ${ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
        with:
          filename: .github/workflow-issue.md
          update_existing: true
          search_existing: open

...
